name: CI/CD Pipeline for py5app
on:
    push:
        branches:
            - main
        paths:
            - src/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to Docker hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Shorten commit_id
                shell: bash
                run: |
                    echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}
            
            -   name: Docker Build and Push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    tags: aumthakkar/py5app:${{ env.COMMIT_ID }}

        outputs:
            commit_id: ${{ env.COMMIT_ID }}

    cd:
        runs-on: self-hosted
        needs: ci
        steps:
            -   name: Checkout Github Repo
                uses: actions/checkout@v6

            - name: Update tag in values.yaml
              run: |
                sudo apt update && sudo apt install python3-pip -y
                pip install yq --break-system-packages
                echo ${{ needs.ci.outputs.commit_id }}
                yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/py5app/values-dev.yaml

            -   name: Commit Change
                uses: EndBug/add-and-commit@v9
                with:
                    message: "pushed the image with tag: ${{ needs.ci.outputs.commit_id }}"

            -   name: Install ArgoCD CLI
                run: |
                    curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v3.2.2/argocd-linux-amd64
                    sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
                    sudo chmod +x /usr/local/bin/argocd

            -   name: ArgoCD login 
                run: |
                    argocd login argocd-server.argocd \
                    --grpc-web \
                    --insecure \
                    --username ${{ secrets.ARGOCD_USERNAME }} \
                    --password ${{ secrets.ARGOCD_PASSWORD }}

            -   name: ArgoCD Repo Create and Sync
                run: |
                    repo="https://github.com/aum-thakkar/py5app.git"
                    argocd repo list ${repo} | grep -q ${repo} || argocd repo add ${repo}

                    # Delete argocd app first if exists to start afresh
                    if argocd app get py5app >/dev/null 2>&1; then
                        echo "Deleting app: py5app"
                        argocd app delete py5app --cascade --yes --wait

                        while argocd app get py5app >/dev/null 2>&1; do
                            echo "Waiting for argocd app: 'py5app' to be deleted..."
                            sleep 2
                        done
                    fi
                    
                    # Create argocd app
                    argocd app create py5app \
                    --dest-namespace dev \
                    --dest-server https://kubernetes.default.svc \
                    --path charts/py5app \
                    --repo ${repo} \
                    --revision main \
                    --sync-option CreateNamespace=true \
                    --sync-policy manual \
                    --values values-dev.yaml

                    argocd app sync py5app
                    argocd app wait py5app --timeout 120







                

